#baseURL = "https://liorz.github.io/blog/"
baseURL = "http://localhost:1313"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "en"
rssLimit = 10
theme = "hugo-texify3"
title = "Lior's Blog"

[pagination]
pagerSize = 5

[taxonomies]
tags = "tags"
categories = "categories"

[params]
title="Lior's Blog"
author = "Lior Zimmerman"
description = "My personal blog"
footnote = """
Powered by  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a> | 
Theme <a class=link href=https://github.com/michaelneuper/hugo-texify3 target=_blank rel=noopener>TeXify3</a>
"""
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
toc = true
rootFontSize = "105%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = true

  [params.commentEngine]
  code = """
<script src="https://giscus.app/client.js"
        data-repo="liorz/blog"
        data-repo-id="R_kgDON5_AVA"
        data-category="General"
        data-category-id="DIC_kwDON5_AVM4CnY0v"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="preferred_color_scheme"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>
  """
  [params.sharingbuttons]
  twitter = true
  email = true
  linkedin = true
  [markup.goldmark.renderer]
   unsafe = true
